# Generated by Django 5.2.1 on 2025-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_robots', models.IntegerField(default=4)),
                ('num_trash', models.IntegerField(default=20)),
                ('grid_size', models.IntegerField(default=32)),
                ('base_x', models.IntegerField(default=0)),
                ('base_y', models.IntegerField(default=0)),
                ('turns_elapsed', models.IntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
